/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Gird: typeof import('./../../src/components/Gird/index.vue')['default']
    GirdItem: typeof import('./../../src/components/Gird/components/GirdItem.vue')['default']
    MChooseArea: typeof import('./../../src/components/mChooseArea/index.vue')['default']
    MChooseIcon: typeof import('./../../src/components/mChooseIcon/index.vue')['default']
    MForm: typeof import('./../../src/components/mForm/index.vue')['default']
    MLoading: typeof import('./../../src/components/mLoading/index.vue')['default']
    MMenu: typeof import('./../../src/components/mMenu/index.vue')['default']
    MTrend: typeof import('./../../src/components/mTrend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../../src/components/searchForm/index.vue')['default']
    SvgIcon: typeof import('./../../src/components/SvgIcon/index.vue')['default']
    TreeFilter: typeof import('./../../src/components/treeFilter/index.vue')['default']
  }
}
