/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElFrom: typeof import('element-plus/es')['ElFrom']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSpce: typeof import('element-plus/es')['ElSpce']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTr: typeof import('element-plus/es')['ElTr']
    ElTree: typeof import('element-plus/es')['ElTree']
    Gird: typeof import('./../components/Gird/index.vue')['default']
    GirdItem: typeof import('./../components/Gird/components/GirdItem.vue')['default']
    MChooseArea: typeof import('./../components/mChooseArea/index.vue')['default']
    MChooseIcon: typeof import('./../components/mChooseIcon/index.vue')['default']
    MForm: typeof import('./../components/mForm/index.vue')['default']
    MLoading: typeof import('./../components/mLoading/index.vue')['default']
    mMenu: typeof import('../components/mMenu/index.vue')['default']
    MMenu: typeof import('./../components/mMenu/index.vue')['default']
    MSvgIcon: typeof import('./../components/mSvgIcon/index.vue')['default']
    MTable: typeof import('./../components/mTable/index.vue')['default']
    MTrend: typeof import('./../components/mTrend/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./../components/searchForm/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TreeFilter: typeof import('./../components/treeFilter/index.vue')['default']
  }
}
